# This pipeline builds and publishes the macOS base image used by the main CI pipeline.
# https://buildkite.com/docs/pipelines/defining-steps
#
# Changes to this file must be manually edited here:
# https://buildkite.com/bun/base-bun-build-macos-darwin/settings/steps

steps:
  - command: |
      echo "$GITHUB_TOKEN" > github_token.txt
      chmod 600 github_token.txt
      chmod +x .buildkite/scripts/ensure-bun-image.sh
      .buildkite/scripts/ensure-bun-image.sh
    label: "Build and Publish Base Image"
    agents:
      queue: darwin

  - command: |
      rm -f github_token.txt
    label: "Cleanup GitHub Token"
    agents:
      queue: darwin 