steps:
  - label: "🩺 Agent VM Health Check"
    key: "agent-vm-health-check"
    command: |
      echo "Running VM health check on agent..."
      ./scripts/agent-vm-health-check.sh check
    agents:
      queue: "darwin"
    timeout_in_minutes: 720
    retry:
      automatic: false
    # Run on ALL darwin agents simultaneously
    parallelism: 10
    
  - label: "📊 Health Check Summary"
    key: "health-check-summary"
    command: |
      echo "=== HEALTH CHECK SUMMARY ==="
      echo "All agents have completed health checks"
      echo "Check individual agent meta-data in Buildkite UI"
    agents:
      queue: "darwin"
      # Run summary on any agent
    depends_on: "agent-vm-health-check" 