steps:
steps:
  - label: ":buildkite: Upload steps"
    command: "buildkite-agent pipeline upload .buildkite/test-pipeline.yml"

  - label: "📦 Clone and List"
    command: |
      echo "--- 📥 Cloning repository"
      git clone https://github.com/oven-sh/bun.git
      cd bun
      
      echo "--- 📋 Listing contents"
      ls -la
      
      echo "--- 📊 Repository info"
      git status
      git log -1
    agents:
      queue: "on-prem"
      arch: "arm64" 