priority: 0
steps:
- 
    key: "ensure-macos-base-vms"
    group: 🔍 Ensure macOS Base VMs
    steps:
    - 
          key: "ensure-macos-vm-13"
          label: 🔍 Ensure macOS 13 base VM exists (all hosts)
          agents:
            queue: darwin
          parallelism: 10
          command: "./scripts/build-macos-vm.sh --release=13 --check-only || ./scripts/build-macos-vm.sh --release=13 --force-oci-rebuild"
          timeout_in_minutes: 60
          retry:
            automatic:
            - 
                      exit_status: "*"
                      limit: 1
              
      
    - 
          key: "ensure-macos-vm-14"
          label: 🔍 Ensure macOS 14 base VM exists (all hosts)
          agents:
            queue: darwin
          parallelism: 10
          command: "./scripts/build-macos-vm.sh --release=14 --check-only || ./scripts/build-macos-vm.sh --release=14 --force-oci-rebuild"
          timeout_in_minutes: 60
          retry:
            automatic:
            - 
                      exit_status: "*"
                      limit: 1
              
      
  
- 
    key: "darwin-aarch64"
    group: ":darwin: aarch64"
    steps:
    - 
          key: "darwin-aarch64-build-cpp"
          label: ":darwin: aarch64 - build-cpp"
          agents:
            queue: darwin
            os: darwin
            arch: arm64
            tart: true
          retry:
            manual:
              permit_on_passed: true
            automatic: false
          cancel_on_build_failing: false
          env:
            BUN_CPP_ONLY: ON
            ENABLE_BASELINE: OFF
            ENABLE_CANARY: ON
            CANARY_REVISION: 1
            CMAKE_VERBOSE_MAKEFILE: ON
            CMAKE_TLS_VERIFY: 0
            MACOS_VM_MEMORY: 8192
            MACOS_VM_CPU: 4
            MACOS_VM_CONFIG_DESCRIPTION: Mac Mini M4 (conservative for stability)
            BUILDKITE_CACHE_TYPE: persistent
            BUILDKITE_CACHE_BASE: "./buildkite-cache"
            BUILDKITE_CACHE_SAVE: ON
            BUILDKITE_CLEAN_CHECKOUT: true
          command:
          - ./scripts/build-macos-vm.sh --release=13
          - ./scripts/ci-macos.sh --release=13 "bun run build:release --target bun && bun run build:release --target dependencies"
      
    - 
          key: "darwin-aarch64-build-zig"
          label: ":darwin: aarch64 - build-zig"
          agents:
            queue: darwin
            os: darwin
            arch: arm64
            tart: true
          retry:
            manual:
              permit_on_passed: true
            automatic: false
          cancel_on_build_failing: false
          env:
            ENABLE_BASELINE: OFF
            ENABLE_CANARY: ON
            CANARY_REVISION: 1
            CMAKE_VERBOSE_MAKEFILE: ON
            CMAKE_TLS_VERIFY: 0
            MACOS_VM_MEMORY: 8192
            MACOS_VM_CPU: 4
            MACOS_VM_CONFIG_DESCRIPTION: Mac Mini M4 (conservative for stability)
            BUILDKITE_CACHE_TYPE: persistent
            BUILDKITE_CACHE_BASE: "./buildkite-cache"
            BUILDKITE_CACHE_SAVE: ON
            BUILDKITE_CLEAN_CHECKOUT: true
          command:
          - ./scripts/build-macos-vm.sh --release=13
          - ./scripts/ci-macos.sh --release=13 "bun run build:release --target bun-zig --toolchain darwin-aarch64"
          timeout_in_minutes: 35
      
    - 
          key: "darwin-aarch64-build-bun"
          label: ":darwin: aarch64 - build-bun"
          depends_on:
          - darwin-aarch64-build-cpp
          - darwin-aarch64-build-zig
          agents:
            queue: darwin
            os: darwin
            arch: arm64
            tart: true
          retry:
            manual:
              permit_on_passed: true
            automatic: false
          cancel_on_build_failing: false
          env:
            BUN_LINK_ONLY: ON
            ENABLE_BASELINE: OFF
            ENABLE_CANARY: ON
            CANARY_REVISION: 1
            CMAKE_VERBOSE_MAKEFILE: ON
            CMAKE_TLS_VERIFY: 0
            MACOS_VM_MEMORY: 8192
            MACOS_VM_CPU: 4
            MACOS_VM_CONFIG_DESCRIPTION: Mac Mini M4 (conservative for stability)
            BUILDKITE_CACHE_TYPE: persistent
            BUILDKITE_CACHE_BASE: "./buildkite-cache"
            BUILDKITE_CACHE_SAVE: ON
            BUILDKITE_CLEAN_CHECKOUT: true
          command:
          - ./scripts/build-macos-vm.sh --release=13
          - ./scripts/ci-macos.sh --release=13 "bun run build:release --target bun"
      
    - 
          key: "darwin-aarch64-14-test-bun"
          label: ":darwin: 14 aarch64 - test-bun"
          depends_on:
          - darwin-aarch64-build-bun
          agents:
            queue: darwin
            os: darwin
            arch: arm64
            tart: true
          retry:
            manual:
              permit_on_passed: true
            automatic: false
          cancel_on_build_failing: false
          parallelism: 2
          timeout_in_minutes: 30
          command:
          - ./scripts/build-macos-vm.sh --release=14
          - ./scripts/runner.node.mjs --step=darwin-aarch64-build-bun
      
    - 
          key: "darwin-aarch64-13-test-bun"
          label: ":darwin: 13 aarch64 - test-bun"
          depends_on:
          - darwin-aarch64-build-bun
          agents:
            queue: darwin
            os: darwin
            arch: arm64
            tart: true
          retry:
            manual:
              permit_on_passed: true
            automatic: false
          cancel_on_build_failing: false
          parallelism: 2
          timeout_in_minutes: 30
          command:
          - ./scripts/build-macos-vm.sh --release=13
          - ./scripts/runner.node.mjs --step=darwin-aarch64-build-bun
      
    depends_on:
    - ensure-macos-vm-13
  
