# Grafana Monitoring Setup Step
# Add this to your pipeline before VM operations to enable monitoring

steps:
  - key: "setup-grafana-monitoring"
    label: "📊 Setup Grafana Monitoring"
    agents:
      queue: "darwin"
    command: |
      echo "🔧 Setting up Grafana monitoring on CI host..."
      ./scripts/setup-grafana-monitoring.sh
    env:
      # These should be set as Buildkite secrets
      GRAFANA_CLOUD_USERNAME: "${GRAFANA_CLOUD_USERNAME}"
      GRAFANA_CLOUD_API_KEY: "${GRAFANA_CLOUD_API_KEY}" 
      GRAFANA_PROMETHEUS_URL: "${GRAFANA_PROMETHEUS_URL}"
      GRAFANA_LOKI_URL: "${GRAFANA_LOKI_URL}"
    timeout_in_minutes: 10
    retry:
      automatic:
        - exit_status: 1
          limit: 2
    # This step should run before any VM operations
    # Add depends_on: ["setup-grafana-monitoring"] to your VM build steps 